name: Deploy Transform Data (JAR)

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo systemctl stop blessrom-sync.service
            # Limpiamos la carpeta target anterior para un despliegue limpio
            sudo rm -rf /opt/blessrom-sync/target

      - name: Copy target folder to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "target/quarkus-app/"
          target: "/opt/blessrom-sync/target/quarkus-app/"
          strip_components: 1

      - name: Start Service on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo systemctl start blessrom-sync.service
            sudo systemctl status blessrom-sync.service --no-pager
